### ISSUE TITLE
fetcher: resume where stopped

### ISSUE THREAD

**Issue by rolinh** [DevMine/crawld#10]
The fetching task always starts with the first repository in the database. It needs to be able to resume from the last processed repository.
I see 2 ways of doing that, a "manual" and an "automatic":
- provide an option in the configuration file to set a 'since_repository_id' parameter
- automatically write to a file the id of the last processed repository

**Comment by gilliek** [comment]
I vote for the "automatic" one. IMHO it's more convenient than setting manually the last ID every time we need to restart the fetcher.

**Comment by rolinh** [comment]
Yes, it is more convenient. The only use-case I see where that would be a problem for the user is if he actually wants to start from the start over again. I guess that in this unusual case, he could just remove the file then.

**Comment by gilliek** [comment]
For that specific use case we can add an option to crawld. Something like "-r" for resume.
